stages:
  - module-pipelines

terraform:
  stage: module-pipelines
  trigger:
    include:
      - local: 'terraform/terraform.yml'
    strategy: depend 
  only:
      changes:
        - terraform/*

helm:
  stage: module-pipelines
  trigger:
    include:
      - local: 'helm/helm.yml'
    strategy: depend 
  only:
      changes:
        - helm/*

charts:
  stage: module-pipelines
  variables: 
    VERSION: $VERSION
  trigger:
    include:
      - local: 'charts/charts.yml'
    strategy: depend 
  only:
      changes:
        - charts/*