stages:
  - module-pipelines

terraform:
  stage: module-pipelines
  trigger:
    include:
      - local: 'terraform/terraform.yml'
    strategy: depend
  rules:
    - changes:
          - terraform/*
    - if: $VERSION
      when: never

helm:
  stage: module-pipelines
  trigger:
    include:
      - local: 'helm/helm.yml'
    strategy: depend
  rules:
    - changes:
          - helm/*
    - if: $VERSION
      when: never

charts:
  stage: module-pipelines
  variables: 
    VERSION: $VERSION
  trigger:
    include:
      - local: 'charts/charts.yml'
    strategy: depend
  rules:
    - changes:
          - charts/*