---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: momo-backend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Values.tag | default .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: momo-store
    env: "{{ .Values.environment }}"
spec:  
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdatemaxUnavailable }}
      maxSurge: {{ .Values.rollingUpdatemaxSurge }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app: backend        
    spec:
      containers:
        - image: {{ .Values.image }}:{{ .Values.tag }}
          name: backend
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: {{ .Values.port }}
          livenessProbe:       
            httpGet:          
              path: /health        
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: {{ .Values.periodSeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            failureThreshold: {{ .Values.failureThreshold }}
      imagePullSecrets:
        - name: docker-config-secret-b
