loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  storage:
    bucketNames:
      chunks: logs
      ruler: logs
      admin: logs
    type: 's3'
    s3:
      s3: http://id:pas@minio.minio.svc.cluster.local:9000
      s3ForcePathStyle: true
test:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
    lokiCanary:
      enabled: false
write:
  replicas: 1
read:
  replicas: 1
backend:
  replicas: 1
singleBinary:
  replicas: 0
ingress:
  enabled: false
gateway:
  enabled: true